services:
  rasa:
    image: rasa/rasa:3.6.4
    ports:
      - 5005:5005
    volumes:
      - ./bot:/app
    command: run -m bot/models --enable-api --cors "*" --debug
  bot:
    image: eaic/ensias-ai-bot:latest
    ports:
      - 1234:1234