services:
  rasa:
    image: rasa/rasa:3.6.4
    ports:
      - 5005:5005
    volumes:
      - ./bot:/app
    command: run -m bot/models --enable-api --cors "*" --debug
  hassan:
    image: eaic/hassan-gpt:1.0
    ports:
      - 1234:1234